jobs:
  build:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Install OpenJDK 17
          command: |
            sudo apt update
            sudo apt install -y openjdk-17-jdk
      - run:
          name: Install Maven
          command: |
            sudo apt install -y maven
      - run:
          name: Verify Java Version
          command: java -version
      - run:
          name: Run Tests
          command: mvn clean test  # Adjust according to your test command

  sonarcloud:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Install OpenJDK 17
          command: |
            sudo apt update
            sudo apt install -y openjdk-17-jdk
      - run:
          name: Install Maven
          command: |
            sudo apt install -y maven
      - run:
          name: Run SonarCloud Analysis
          command: |
            mvn clean verify sonar:sonar \
              -Dsonar.projectKey=jamie-vc \
              -Dsonar.organization=Jamie-vc \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN
