version: 2.1

executors:
  java-executor:
    docker:
       - image: openjdk:17
    working_directory: ~/repo

jobs:
  build:
    docker:
      - image: circleci/openjdk:17  # Ensure the image is correct
    steps:
      - checkout  # Check out the code
      - run:
          name: Build with Maven
          command: mvn clean install  # Replace with the correct build tool



  sonar:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Install unzip (Debian-based)
          command: |
            sudo apt-get update && sudo apt-get install -y unzip
      - run:
          name: Install Maven dependencies
          command: mvn install
      - run:
          name: Run SonarQube Analysis
          command: mvn sonar:sonar -Dsonar.projectKey=my-app -Dsonar.host.url=https://sonarcloud.io

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
