version: 2.1

executors:
  java-executor:
    docker:
      - image: openjdk:17  # Use the official OpenJDK 17 image
    working_directory: ~/repo

jobs:
  build:
    executor: java-executor
    steps:
      - checkout  # Check out the source code
      - run:
          name: Install unzip
          command: sudo apt-get update && sudo apt-get install -y unzip  # Install unzip
      - run:
          name: Set up Maven
          command: |
            curl -sSL https://get.sdkman.io | bash
            source ~/.sdkman/bin/sdkman-init.sh
            sdk install maven
      - run:
          name: Build the project
          command: mvn clean install

  sonar:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Install Maven dependencies
          command: mvn install
      - run:
          name: Run SonarQube Analysis
          command: mvn sonar:sonar -Dsonar.projectKey=my-app -Dsonar.host.url=https://sonarcloud.io

workflows:
  version: 2
  build_and_analyze:
    jobs:
      - build
      - sonar:
          requires:
            - build
