version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0  # Updated to a valid image tag
    steps:
      - checkout

      - run:
          name: Install unzip
          command: sudo apt-get update && sudo apt-get install -y unzip

      - run:
          name: Install SDKMAN
          command: curl -sSL https://get.sdkman.io | bash

      - run:
          name: Source SDKMAN
          command: echo "source $HOME/.sdkman/bin/sdkman-init.sh" >> $BASH_ENV && source $BASH_ENV

      - run:
          name: List available Java versions on SDKMAN
          command: source $BASH_ENV && sdk list java

      - run:
          name: Install Java with SDKMAN
          command: sdk install java 17.0.7-open  # Replace with a valid version found in previous step

      - run:
          name: Build project
          command: ./gradlew build

      - run:
          name: Run SonarQube Analysis
          command: ./gradlew sonarqube -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${SONAR_TOKEN}

workflows:
  version: 2
  build_and_analyze:
    jobs:
      - build
