version: 2.1

jobs:
  sonarcloud:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run:
          name: Run SonarQube Analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey=jamie-vc \
              -Dsonar.organization=Jamie-vc \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  sonarcloud:
    jobs:
      - sonarcloud
