version: 2.1

executors:
  java-executor:
    docker:
      - image: cimg/openjdk:17.0  # Updated to use the official CircleCI-maintained image

jobs:
  build:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Verify Java Version
          command: java -version
      - run:
          name: Run Tests
          command: mvn clean test  # Your test command

  sonarcloud:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Run SonarCloud Analysis
          command: |
            mvn clean verify sonar:sonar \
              -Dsonar.projectKey=jamie-vc \
              -Dsonar.organization=Jamie-vc \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  build-and-sonarcloud:
    jobs:
      - build
      - sonarcloud:
          requires:
            - build
