version: 2.1

jobs:
  build:
    docker:
      # Use the official OpenJDK 17 image from Docker Hub
      - image: openjdk:17
    steps:
      # Checkout the code from the repository
      - checkout

      # Set up Maven
      - run:
          name: Set up Maven
          command: |
            curl -sSL https://get.sdkman.io | bash
            source ~/.sdkman/bin/sdkman-init.sh
            sdk install maven

      # Build the project
      - run:
          name: Build the project
          command: mvn clean install  # Replace with your actual build command (e.g., gradle build)

  sonar:
    docker:
      # Use the official OpenJDK 17 image for SonarQube analysis
      - image: openjdk:17
    steps:
      # Checkout the code again in the Sonar job
      - checkout

      # Run SonarQube Analysis
      - run:
          name: Run SonarQube Analysis
          command: |
            mvn sonar:sonar -Dsonar.projectKey=my-app -Dsonar.host.url=https://sonarcloud.io

workflows:
  version: 2
  build_and_analyze:
    jobs:
      - build
      - sonar:
          requires:
            - build
