version: 2.1

executors:
  java-executor:
    docker:
      - image: circleci/openjdk:17-jdk
    working_directory: ~/repo  # Assuming pom.xml is here

jobs:
  build:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Verify Directory and Check POM
          command: |
            ls -la  # Verify files in the directory
            mvn clean test  # Run Maven tests if POM is found

  sonarcloud:
    docker:
      - image: circleci/openjdk:17-jdk
    steps:
      - checkout
      - run:
          name: Run SonarCloud Analysis
          command: |
            mvn clean verify sonar:sonar \
              -Dsonar.projectKey=jamie-vc \
              -Dsonar.organization=Jamie-vc \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  build-and-sonarcloud:
    jobs:
      - build
      - sonarcloud:
          requires:
            - build
