version: 2.1

executors:
  java-executor:
    docker:
       - image: openjdk:17
    working_directory: ~/repo

jobs:
  build:
    docker:
      - image: circleci/openjdk:17  # Ensure you're using the correct image for Java 17
    steps:
      - checkout  # Checkout the project
      - run:
          name: Install unzip
          command: |
            sudo apt-get update
            sudo apt-get install -y unzip
      - run:
          name: Set up SDKMAN and Maven
          command: |
            curl -sSL https://get.sdkman.io | bash
            source ~/.sdkman/bin/sdkman-init.sh
            sdk install maven
      - run:
          name: Build project with Maven
          command: mvn clean install


  sonar:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Install unzip (Debian-based)
          command: |
            sudo apt-get update && sudo apt-get install -y unzip
      - run:
          name: Install Maven dependencies
          command: mvn install
      - run:
          name: Run SonarQube Analysis
          command: mvn sonar:sonar -Dsonar.projectKey=my-app -Dsonar.host.url=https://sonarcloud.io

workflows:
  version: 2
  build_and_analyze:
    jobs:
      - build
      - sonar:
          requires:
            - build
