version: 2.1

jobs:
  sonarcloud:
    docker:
      - image: circleci/python:3.8  # Use a basic CircleCI Docker image with Python (you can modify based on your needs)
    steps:
      # Checkout your repository
      - checkout

      # Install SonarScanner version 4.6.2
      - run:
          name: Install SonarScanner 4.6.2
          command: |
            curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
            unzip sonar-scanner.zip
            sudo mv sonar-scanner-4.6.2.2472-linux /opt/sonar-scanner
            sudo ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner

      # Run SonarQube Analysis
      - run:
          name: Run SonarQube Analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey=jamie-vc \
              -Dsonar.organization=Jamie-vc \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  sonarcloud:
    jobs:
      - sonarcloud
